### ISSUE TITLE
ValueError: min() arg is an empty sequence

### ISSUE THREAD

**Issue by vstaf** [gamenet/redis-memory-analyzer#12]
Got another crash today
```
Traceback (most recent call last):
  File "/usr/bin/rma", line 9, in <module>
    load_entry_point('rma==0.1.5', 'console_scripts', 'rma')()
  File "/usr/lib/python3.5/site-packages/rma/cli/rma_cli.py", line 95, in main
    app.run()
  File "/usr/lib/python3.5/site-packages/rma/application.py", line 121, in run
    str_res += self.do_ram(keys)
  File "/usr/lib/python3.5/site-packages/rma/application.py", line 155, in do_ram
    ret += (rule.analyze(aggregate_patterns))
  File "/usr/lib/python3.5/site-packages/rma/rule/List.py", line 75, in analyze
    agg = ListAggregator((ListStatEntry(x, self.redis) for x in data), len(data))
  File "/usr/lib/python3.5/site-packages/rma/rule/List.py", line 43, in __init__
    self.encoding = pref_encoding([obj.encoding for obj in encode_iter], redis_encoding_id_to_str)
  File "/usr/lib/python3.5/site-packages/rma/rule/List.py", line 43, in <listcomp>
    self.encoding = pref_encoding([obj.encoding for obj in encode_iter], redis_encoding_id_to_str)
  File "/usr/lib/python3.5/site-packages/rma/rule/List.py", line 75, in <genexpr>
    agg = ListAggregator((ListStatEntry(x, self.redis) for x in data), len(data))
  File "/usr/lib/python3.5/site-packages/rma/rule/List.py", line 33, in __init__
    self.valueMin = min(min_iter)
ValueError: min() arg is an empty sequence

```

**Comment by fenelon** [comment]
Getting the same issue on 0.1.13:

```
Match *: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 4995001/5000000 [01:27<00:00, 53299.06it/s]INFO:root:
Limit 5000000 reached

Aggregating keys by pattern and type

Apply rules
Processing keys:   0%|                                                                                                                                                      | 0/355 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/rma", line 9, in <module>
    load_entry_point('rma==0.1.13', 'console_scripts', 'rma')()
  File "/usr/local/lib/python3.5/site-packages/rma-0.1.13-py3.5.egg/rma/cli/rma_cli.py", line 92, in main
  File "/usr/local/lib/python3.5/site-packages/rma-0.1.13-py3.5.egg/rma/application.py", line 118, in run
  File "/usr/local/lib/python3.5/site-packages/rma-0.1.13-py3.5.egg/rma/application.py", line 153, in do_ram
  File "/usr/local/lib/python3.5/site-packages/rma-0.1.13-py3.5.egg/rma/rule/KeyString.py", line 57, in analyze
ValueError: min() arg is an empty sequence
```

**Comment by misterion** [comment]
Here is new issue with KeyString rule. Could you submit new issue?

**Comment by fenelon** [comment]
@misterion extracted as #23. The fix did something but the problem stays.
