### ISSUE TITLE
Got error after 

### ISSUE THREAD

**Issue by FarzanRNobakht** [gamenet/redis-memory-analyzer#33]
after installing with
pip install rma
executing rma --help ends with 
it seems i have a missing dipendency but i cannot understant
```
Traceback (most recent call last):
  File "/usr/bin/rma", line 9, in <module>
    load_entry_point('rma==0.1.16', 'console_scripts', 'rma')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/rma/__init__.py", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rma-0.1.16-py2.7.egg/rma/application.py", line 145
    self.reporter.print(str_res)
```

**Comment by tscholak** [comment]
Same issue. Some rma version. For some reason, `self.reporter.print(str_res)` in `application.py` is wrong syntax.

**Comment by tscholak** [comment]
Never mind, I was running it with the wrong version of Python

**Comment by joshuaflanagan** [comment]
What do you mean by "wrong version of python". I am also seeing this error using python 2.7.10 that comes with macOS Sierra.
What did you do to fix it?

**Comment by tscholak** [comment]
I didn't see it at first at the time, but it is stated very clearly in the repo's `Readme.md`:
```
Pre-Requisites :
python >= 3.4 and pip.
```

**Comment by joshuaflanagan** [comment]
Ha, you're right. I had read the readme, and re-read it when you mentioned "wrong version", and still hadn't noticed.

**Comment by Dadibom** [comment]
I've got 3.5.x preinstalled in ubuntu, but rma still ends up under 2.7 when installing with pip. any way to fix this?
