### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by soulfly** [gamenet/redis-memory-analyzer#34]
I installed rma via **pip install rma**

but then getting the error when trying to run:

```
[06:48]  # rma --help
Traceback (most recent call last):
  File "/usr/local/bin/rma", line 9, in <module>
    load_entry_point('rma==0.1.16', 'console_scripts', 'rma')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/rma/__init__.py", line 1, in <module>
    from rma.application import RmaApplication
  File "/usr/local/lib/python2.7/site-packages/rma/application.py", line 145
    self.reporter.print(str_res)
                      ^
SyntaxError: invalid syntax
```

I have Python 2.7.10 installed

**Comment by soulfly** [comment]
Ok I see python >= 3.4 and pip.
