### ISSUE TITLE
invalid syntax: self.reporter.print(str_res) 

### ISSUE THREAD

**Issue by sshilko** [gamenet/redis-memory-analyzer#36]
[root@ip-XX ec2-user]# pip install rma
Collecting rma
  Downloading rma-0.1.16.zip (41kB)
    100% |████████████████████████████████| 51kB 7.5MB/s
Collecting redis (from rma)
  Downloading redis-2.10.6-py2.py3-none-any.whl (64kB)
    100% |████████████████████████████████| 71kB 9.1MB/s
Collecting tabulate (from rma)
  Downloading tabulate-0.8.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 10.6MB/s
Collecting tqdm (from rma)
  Downloading tqdm-4.19.4-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 9.5MB/s
Collecting msgpack-python (from rma)
  Downloading msgpack-python-0.4.8.tar.gz (113kB)
    100% |████████████████████████████████| 122kB 9.3MB/s
Installing collected packages: redis, tabulate, tqdm, msgpack-python, rma
  Running setup.py install for tabulate ... done
  Running setup.py install for msgpack-python ... done
  Running setup.py install for rma ... done
Successfully installed msgpack-python-0.4.8 redis-2.10.6 rma-0.1.16 tabulate-0.8.2 tqdm-4.19.4
[root@ip-XX ec2-user]# rma

[ec2-user@ip-XX ~]$ rma --help
Traceback (most recent call last):
  File "/usr/local/bin/rma", line 11, in <module>
    load_entry_point('rma==0.1.16', 'console_scripts', 'rma')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/rma/__init__.py", line 1, in <module>
    from rma.application import RmaApplication
  File "/usr/local/lib/python2.7/site-packages/rma/application.py", line 145
    self.reporter.print(str_res)
                      ^
SyntaxError: invalid syntax
[ec2-user@ip-XX ~]$ cat /etc/issue
Amazon Linux AMI release 2017.09
Kernel \r on an \m

**Comment by Dadibom** [comment]
You need python 3.4, you're using 2.7

**Comment by sshilko** [comment]
Okay
