### ISSUE TITLE
Hitting recursion limit

### ISSUE THREAD

**Issue by dsandber** [gamenet/redis-memory-analyzer#39]
`Aggregating keys by pattern and type
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/rma", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/cli/rma_cli.py", line 97, in main
    app.run()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/application.py", line 133, in run
    keys = {k: self.get_pattern_aggregated_data(v) for k, v in keys.items()}
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/application.py", line 133, in <dictcomp>
    keys = {k: self.get_pattern_aggregated_data(v) for k, v in keys.items()}
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/application.py", line 181, in get_pattern_aggregated_data
    split_patterns = self.splitter.split((ptransform(obj["name"]) for obj in data))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 32, in split
    return self.unfold_to_list(pass2, separator)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 82, in unfold_to_list
    for compound_key in dict_build(sub_tree):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build
    for d in dict_build(value, pre=pre+[key]):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build
    for d in dict_build(value, pre=pre+[key]):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build
    for d in dict_build(value, pre=pre+[key]):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build
    for d in dict_build(value, pre=pre+[key]):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build
    for d in dict_build(value, pre=pre+[key]):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/rma/splitter.py", line 10, in dict_build`

**Comment by dsandber** [comment]
RecursionError: maximum recursion depth exceeded
