### ISSUE TITLE
Doesn't work with Redis on Memorystore GCP

### ISSUE THREAD

**Issue by ilmatley** [gamenet/redis-memory-analyzer#41]
### When trying to run on gcp:

rma -s 10.0.0.3
Match *:   0%|                                                                                                                    | 0/34 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/rma", line 9, in <module>
    load_entry_point('rma==0.1.16', 'console_scripts', 'rma')()
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/cli/rma_cli.py", line 97, in main
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/application.py", line 127, in run
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/scanner.py", line 85, in scan
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/scanner.py", line 53, in batch_scan
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/scanner.py", line 61, in resolve_types
  File "/usr/local/lib/python3.5/dist-packages/rma-0.1.16-py3.5.egg/rma/scanner.py", line 58, in resolve_types
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 3498, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 2704, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.5/dist-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.5/dist-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: Error running script (call to f_b89215e5d8808de13e1c715aaedbb744ce4536e7): @user_script:5: @user_script: 5: Unknown Redis command called from Lua script

Any ideas ?

**Comment by ilmatley** [comment]
Nothing ?

**Comment by splap** [comment]
Same problem here.
