### ISSUE TITLE
re.error: bad character range y-m at position 167

### ISSUE THREAD

**Issue by kamal2222ahmed** [gamenet/redis-memory-analyzer#42]
rma -s bg-redis.x.x.x.x -p 6379 -a password
Match *: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 378067/378654 [04:42<00:00, 1337.09it/s]

Aggregating keys by pattern and type
Traceback (most recent call last):
  File "/Users/syedahmed/anaconda3/bin/rma", line 11, in <module>
    sys.exit(main())
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/rma/cli/rma_cli.py", line 97, in main
    app.run()
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/rma/application.py", line 133, in run
    keys = {k: self.get_pattern_aggregated_data(v) for k, v in keys.items()}
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/rma/application.py", line 133, in <dictcomp>
    keys = {k: self.get_pattern_aggregated_data(v) for k, v in keys.items()}
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/rma/application.py", line 186, in get_pattern_aggregated_data
    aggregate_patterns[pattern] = list(filter(lambda obj: fnmatch.fnmatch(ptransform(obj["name"]), pattern), data))
  File "/Users/syedahmed/anaconda3/lib/python3.7/site-packages/rma/application.py", line 186, in <lambda>
    aggregate_patterns[pattern] = list(filter(lambda obj: fnmatch.fnmatch(ptransform(obj["name"]), pattern), data))
  File "/Users/syedahmed/anaconda3/lib/python3.7/fnmatch.py", line 36, in fnmatch
    return fnmatchcase(name, pat)
  File "/Users/syedahmed/anaconda3/lib/python3.7/fnmatch.py", line 70, in fnmatchcase
    match = _compile_pattern(pat)
  File "/Users/syedahmed/anaconda3/lib/python3.7/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/Users/syedahmed/anaconda3/lib/python3.7/re.py", line 234, in compile
    return _compile(pattern, flags)
  File "/Users/syedahmed/anaconda3/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_parse.py", line 816, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/Users/syedahmed/anaconda3/lib/python3.7/sre_parse.py", line 580, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
re.error: bad character range y-m at position 167

**Comment by misterion** [comment]
Could you please try with v0.2? After https://github.com/gamenet/redis-memory-analyzer/pull/38 merge it should be fixed.
